package main

var Program1 = []any{
	1,
	2,
	3,
	4,
	"data string",
	"A",
	"B",
	"C",
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) + 1 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) + 1 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) - 1 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) - 1 },
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) + 1 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) + 1 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) - 1 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) - 1 },
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) + 1 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) + 1 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) - 1 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) - 1 },
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) + 1 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) + 1 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) - 1 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) - 1 },
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) + 1 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) + 1 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) - 1 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) - 1 },
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) + 1 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) + 1 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) - 1 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) - 1 },
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) + 1 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) + 1 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) - 1 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) - 1 },
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) + 1 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) + 1 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) - 1 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) - 1 },
}

var Program2 = []any{
	func() { cpu.Registers["$t0"] = 1 },
	func() { cpu.Registers["$t1"] = 1 },
	func() { cpu.Registers["$t2"] = 1 },
	func() { cpu.Registers["$t3"] = 1 },
	func() { cpu.Registers["$t0"] = cpu.Registers["$t0"].(int) * 2 },
	func() { cpu.Registers["$t1"] = cpu.Registers["$t1"].(int) * 3 },
	func() { cpu.Registers["$t2"] = cpu.Registers["$t2"].(int) * 4 },
	func() { cpu.Registers["$t3"] = cpu.Registers["$t3"].(int) * 5 },
}

var Program3 = []any{
	func() { cpu.Registers["$t0"] = "A" },
	func() { cpu.Registers["$t1"] = "A" },
	func() { cpu.Registers["$t2"] = "A" },
	func() { cpu.Registers["$t3"] = "A" },
	func() { cpu.Registers["$t0"] = "A" },
	func() { cpu.Registers["$t1"] = "A" },
	func() { cpu.Registers["$t2"] = "A" },
	func() { cpu.Registers["$t3"] = "A" },
}

var Program4 = []any{
	func() { cpu.Registers["$t0"] = 13 },
	func() { cpu.Registers["$t1"] = 13 },
	func() { cpu.Registers["$t2"] = 13 },
	func() { cpu.Registers["$t3"] = 13 },
	func() { cpu.Registers["$t0"] = 13 },
	func() { cpu.Registers["$t1"] = 13 },
	func() { cpu.Registers["$t2"] = 13 },
	func() { cpu.Registers["$t3"] = 13 },
}
